name: 'evotech-bot'
description: 'evotech-bot'

inputs:
  openai-api-key:
    description: 'openai-api-key'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create branch
      run: |
        git checkout -b BRANCH_NAME
        git push origin BRANCH_NAME
      shell: bash
    - name: Install OpenAI package
      run: pip install -r requirements.txt
      shell: bash
    - name: Call model
      run: |
        python main.py
      shell: bash
    - name: Commit changes
      run: |
        git config --global user.email "bot@evotech.com"
        git config --global user.name "evotech bot"
        git commit -am "evotech recommendation"
      shell: bash
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5.0.0
      with:
        title: Evotech recommendation
        body: Evotech recommendation
        branch: BRANCH_NAME
        base: main
